# Generated by Django 3.2.16 on 2022-11-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_alter_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='wd_type',
            new_name='wd_code',
        ),
    ]
